job.type: train
dataset.name: fb15k-237

train:
  batch_size: 1000
  loss: ce
  optimizer: Adam
  optimizer_args:
    lr: 0.01
  type: negative_sampling
  max_epochs: 5

eval:
  batch_size: 2000

negative_sampling:
  num_samples.s: 1  # default: p=0; o=s
  num_samples.o: 1
  sampling_type: uniform

model: distmult
lookup_embedder:
  dim: 256
  initialize: uniform_
  initialize_args:
    uniform_:
      a: -0.85
      b: 0.85